blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Community Discussions
    url: https://github.com/bubbaaz/devbox/discussions
    about: Please use discussions for general questions or brainstorming.
